var chart_util = {
		constant:{
			formatter_check_num:"num",
			formatter_check_percent:"percent"
		},
		axisLabelFormatterType:function(fields){
			var _this = this;
			var type = _this.constant.formatter_check_num;
			if(this.hasFieldFormatter(_this.constant.formatter_check_percent, fields)){
				type = _this.constant.formatter_check_percent;
			}
			return type;
		},
		getShowName:function(field){
			var show_name = "";
			if(field.new_alias_name){
				show_name = field.new_alias_name;
			}else{
				show_name = field.alias_name;
			}
			return show_name;
		},
		hasFieldFormatter:function(check,fields){
			var flag  = false;
			if(fields && fields.length > 0){
				for(var i = 0;i<fields.length;i++){
					var d = fields[i];
					var formatter = d.formatter;
					if(formatter){
						if(check == formatter.check){
							flag = true;
							break;
						}
					}
				}
			}
			return flag;
		},
		setFormatterAndUnit:function(axis,data){
			var seriy_data = [];
			if(data && data.length > 0){
				for(var i = 0 ;i < data.length;i++){
					data[i].formatter = axis.formatter;
					data[i].unit = axis.unit;
					seriy_data.push(data[i]);
				}
			}
			return seriy_data;
		}
};


function chartDataClone(Obj) {
    var buf;   
    if (Obj instanceof Array) {
        buf = [];  // 创建一个空的数组
        var i = Obj.length;
        while (i--) {
            buf[i] = chartDataClone(Obj[i]);
        }
        return buf;
    } else if (Obj instanceof Object){
        buf = {};  // 创建一个空对象
        for (var k in Obj) {  // 为这个对象添加新的属性
            buf[k] = chartDataClone(Obj[k]);
        }
        return buf;
    }else{
        return Obj;
    }
}

var  chart_utils_test = function(){
	return "123";
}

var province_data = [
                     {name: '北京',value:0 },
                     {name: '天津',value:0 },
                     {name: '上海',value:0 },
                     {name: '重庆',value:0 },
                     {name: '河北',value:0 },
                     {name: '河南',value:0 },
                     {name: '云南',value:0 },
                     {name: '辽宁',value:0 },
                     {name: '黑龙江',value:0 },
                     {name: '湖南',value:0 },
                     {name: '安徽',value:0 },
                     {name: '山东',value:0 },
                     {name: '新疆',value:0 },
                     {name: '江苏',value:0 },
                     {name: '浙江',value:0 },
                     {name: '江西',value:0 },
                     {name: '湖北',value:0 },
                     {name: '广西',value:0 },
                     {name: '甘肃',value:0 },
                     {name: '山西',value:0 },
                     {name: '内蒙古',value:0 },
                     {name: '陕西',value:0 },
                     {name: '吉林',value:0 },
                     {name: '福建',value:0 },
                     {name: '贵州',value:0 },
                     {name: '广东',value:0 },
                     {name: '青海',value:0 },
                     {name: '西藏',value:0 },
                     {name: '四川',value:0 },
                     {name: '宁夏',value:0 },
                     {name: '海南',value:0 },
                     {name: '台湾',value:0 },
                     {name: '香港',value:0 },
                     {name: '澳门',value:0 },
                     {name: '南海诸岛',value:0 }
                 ];
var province_city = [
	{city : '北京',province :'北京'},
	{city : '天津',province :'天津'},
	{city : '上海',province :'上海'},
	{city : '重庆',province :'重庆'},
	{city : '石家庄',province :'河北'},
	{city : '唐山',province :'河北'},
	{city : '秦皇岛',province :'河北'},
	{city : '邯郸',province :'河北'},
	{city : '邢台',province :'河北'},
	{city : '保定',province :'河北'},
	{city : '张家口',province :'河北'},
	{city : '承德',province :'河北'},
	{city : '沧州',province :'河北'},
	{city : '廊坊',province :'河北'},
	{city : '衡水',province :'河北'},
	{city : '太原',province :'山西'},
	{city : '大同',province :'山西'},
	{city : '阳泉',province :'山西'},
	{city : '长治',province :'山西'},
	{city : '晋城',province :'山西'},
	{city : '朔州',province :'山西'},
	{city : '晋中',province :'山西'},
	{city : '运城',province :'山西'},
	{city : '忻州',province :'山西'},
	{city : '临汾',province :'山西'},
	{city : '吕梁',province :'山西'},
	{city : '呼和浩特',province :'内蒙古'},
	{city : '包头',province :'内蒙古'},
	{city : '乌海',province :'内蒙古'},
	{city : '赤峰',province :'内蒙古'},
	{city : '通辽',province :'内蒙古'},
	{city : '鄂尔多斯',province :'内蒙古'},
	{city : '呼伦贝尔',province :'内蒙古'},
	{city : '兴安盟',province :'内蒙古'},
	{city : '锡林郭勒盟',province :'内蒙古'},
	{city : '乌兰察布盟',province :'内蒙古'},
	{city : '巴彦淖尔盟',province :'内蒙古'},
	{city : '阿拉善盟',province :'内蒙古'},
	{city : '沈阳',province :'辽宁'},
	{city : '大连',province :'辽宁'},
	{city : '鞍山',province :'辽宁'},
	{city : '抚顺',province :'辽宁'},
	{city : '本溪',province :'辽宁'},
	{city : '丹东',province :'辽宁'},
	{city : '锦州',province :'辽宁'},
	{city : '营口',province :'辽宁'},
	{city : '阜新',province :'辽宁'},
	{city : '辽阳',province :'辽宁'},
	{city : '盘锦',province :'辽宁'},
	{city : '铁岭',province :'辽宁'},
	{city : '朝阳',province :'辽宁'},
	{city : '葫芦岛',province :'辽宁'},
	{city : '长春',province :'吉林'},
	{city : '吉林',province :'吉林'},
	{city : '四平',province :'吉林'},
	{city : '辽源',province :'吉林'},
	{city : '通化',province :'吉林'},
	{city : '白山',province :'吉林'},
	{city : '松原',province :'吉林'},
	{city : '白城',province :'吉林'},
	{city : '延边朝鲜族自治州',province :'吉林'},
	{city : '哈尔滨',province :'黑龙江'},
	{city : '齐齐哈尔',province :'黑龙江'},
	{city : '鸡西',province :'黑龙江'},
	{city : '鹤岗',province :'黑龙江'},
	{city : '双鸭山',province :'黑龙江'},
	{city : '大庆',province :'黑龙江'},
	{city : '伊春',province :'黑龙江'},
	{city : '佳木斯',province :'黑龙江'},
	{city : '七台河',province :'黑龙江'},
	{city : '牡丹江',province :'黑龙江'},
	{city : '黑河',province :'黑龙江'},
	{city : '绥化',province :'黑龙江'},
	{city : '大兴安岭',province :'黑龙江'},
	{city : '南京',province :'江苏'},
	{city : '无锡',province :'江苏'},
	{city : '徐州',province :'江苏'},
	{city : '常州',province :'江苏'},
	{city : '苏州',province :'江苏'},
	{city : '南通',province :'江苏'},
	{city : '连云港',province :'江苏'},
	{city : '淮安',province :'江苏'},
	{city : '盐城',province :'江苏'},
	{city : '扬州',province :'江苏'},
	{city : '镇江',province :'江苏'},
	{city : '泰州',province :'江苏'},
	{city : '宿迁',province :'江苏'},
	{city : '杭州',province :'浙江'},
	{city : '宁波',province :'浙江'},
	{city : '温州',province :'浙江'},
	{city : '嘉兴',province :'浙江'},
	{city : '湖州',province :'浙江'},
	{city : '绍兴',province :'浙江'},
	{city : '金华',province :'浙江'},
	{city : '衢州',province :'浙江'},
	{city : '舟山',province :'浙江'},
	{city : '台州',province :'浙江'},
	{city : '丽水',province :'浙江'},
	{city : '合肥',province :'安徽'},
	{city : '芜湖',province :'安徽'},
	{city : '蚌埠',province :'安徽'},
	{city : '淮南',province :'安徽'},
	{city : '马鞍山',province :'安徽'},
	{city : '淮北',province :'安徽'},
	{city : '铜陵',province :'安徽'},
	{city : '安庆',province :'安徽'},
	{city : '黄山',province :'安徽'},
	{city : '滁州',province :'安徽'},
	{city : '阜阳',province :'安徽'},
	{city : '宿州',province :'安徽'},
	{city : '巢湖',province :'安徽'},
	{city : '六安',province :'安徽'},
	{city : '亳州',province :'安徽'},
	{city : '池州',province :'安徽'},
	{city : '宣城',province :'安徽'},
	{city : '福州',province :'福建'},
	{city : '厦门',province :'福建'},
	{city : '莆田',province :'福建'},
	{city : '三明',province :'福建'},
	{city : '泉州',province :'福建'},
	{city : '漳州',province :'福建'},
	{city : '南平',province :'福建'},
	{city : '龙岩',province :'福建'},
	{city : '宁德',province :'福建'},
	{city : '南昌',province :'江西'},
	{city : '景德镇',province :'江西'},
	{city : '萍乡',province :'江西'},
	{city : '九江',province :'江西'},
	{city : '新余',province :'江西'},
	{city : '鹰潭',province :'江西'},
	{city : '赣州',province :'江西'},
	{city : '吉安',province :'江西'},
	{city : '宜春',province :'江西'},
	{city : '抚州',province :'江西'},
	{city : '上饶',province :'江西'},
	{city : '济南',province :'山东'},
	{city : '青岛',province :'山东'},
	{city : '淄博',province :'山东'},
	{city : '枣庄',province :'山东'},
	{city : '东营',province :'山东'},
	{city : '烟台',province :'山东'},
	{city : '潍坊',province :'山东'},
	{city : '济宁',province :'山东'},
	{city : '泰安',province :'山东'},
	{city : '威海',province :'山东'},
	{city : '日照',province :'山东'},
	{city : '莱芜',province :'山东'},
	{city : '临沂',province :'山东'},
	{city : '德州',province :'山东'},
	{city : '聊城',province :'山东'},
	{city : '滨州',province :'山东'},
	{city : '菏泽',province :'山东'},
	{city : '郑州',province :'河南'},
	{city : '开封',province :'河南'},
	{city : '洛阳',province :'河南'},
	{city : '平顶山',province :'河南'},
	{city : '安阳',province :'河南'},
	{city : '鹤壁',province :'河南'},
	{city : '新乡',province :'河南'},
	{city : '焦作',province :'河南'},
	{city : '濮阳',province :'河南'},
	{city : '许昌',province :'河南'},
	{city : '漯河',province :'河南'},
	{city : '三门峡',province :'河南'},
	{city : '南阳',province :'河南'},
	{city : '商丘',province :'河南'},
	{city : '信阳',province :'河南'},
	{city : '周口',province :'河南'},
	{city : '驻马店',province :'河南'},
	{city : '济源',province :'河南'},
	{city : '武汉',province :'湖北'},
	{city : '黄石',province :'湖北'},
	{city : '十堰',province :'湖北'},
	{city : '宜昌',province :'湖北'},
	{city : '襄阳',province :'湖北'},
	{city : '鄂州',province :'湖北'},
	{city : '荆门',province :'湖北'},
	{city : '孝感',province :'湖北'},
	{city : '荆州',province :'湖北'},
	{city : '黄冈',province :'湖北'},
	{city : '咸宁',province :'湖北'},
	{city : '随州',province :'湖北'},
	{city : '恩施土家族苗族自治州',province :'湖北'},
	{city : '仙桃',province :'湖北'},
	{city : '潜江',province :'湖北'},
	{city : '天门',province :'湖北'},
	{city : '神农架',province :'湖北'},
	{city : '长沙',province :'湖南'},
	{city : '株洲',province :'湖南'},
	{city : '湘潭',province :'湖南'},
	{city : '衡阳',province :'湖南'},
	{city : '邵阳',province :'湖南'},
	{city : '岳阳',province :'湖南'},
	{city : '常德',province :'湖南'},
	{city : '张家界',province :'湖南'},
	{city : '益阳',province :'湖南'},
	{city : '郴州',province :'湖南'},
	{city : '永州',province :'湖南'},
	{city : '怀化',province :'湖南'},
	{city : '娄底',province :'湖南'},
	{city : '湘西土家族苗族自治州',province :'湖南'},
	{city : '广州',province :'广东'},
	{city : '韶关',province :'广东'},
	{city : '深圳',province :'广东'},
	{city : '珠海',province :'广东'},
	{city : '汕头',province :'广东'},
	{city : '佛山',province :'广东'},
	{city : '江门',province :'广东'},
	{city : '湛江',province :'广东'},
	{city : '茂名',province :'广东'},
	{city : '肇庆',province :'广东'},
	{city : '惠州',province :'广东'},
	{city : '梅州',province :'广东'},
	{city : '汕尾',province :'广东'},
	{city : '河源',province :'广东'},
	{city : '阳江',province :'广东'},
	{city : '清远',province :'广东'},
	{city : '东莞',province :'广东'},
	{city : '中山',province :'广东'},
	{city : '潮州',province :'广东'},
	{city : '揭阳',province :'广东'},
	{city : '云浮',province :'广东'},
	{city : '南宁',province :'广西'},
	{city : '桂林',province :'广西'},
	{city : '梧州',province :'广西'},
	{city : '北海',province :'广西'},
	{city : '防城港',province :'广西'},
	{city : '钦州',province :'广西'},
	{city : '贵港',province :'广西'},
	{city : '玉林',province :'广西'},
	{city : '百色',province :'广西'},
	{city : '贺州',province :'广西'},
	{city : '河池',province :'广西'},
	{city : '来宾',province :'广西'},
	{city : '崇左',province :'广西'},
	{city : '柳州',province :'广西'},
	{city : '海口',province :'海南'},
	{city : '三亚',province :'海南'},
	{city : '其他',province :'海南'},
	{city : '成都',province :'四川'},
	{city : '自贡',province :'四川'},
	{city : '攀枝花',province :'四川'},
	{city : '泸州',province :'四川'},
	{city : '德阳',province :'四川'},
	{city : '绵阳',province :'四川'},
	{city : '广元',province :'四川'},
	{city : '遂宁',province :'四川'},
	{city : '内江',province :'四川'},
	{city : '乐山',province :'四川'},
	{city : '南充',province :'四川'},
	{city : '眉山',province :'四川'},
	{city : '宜宾',province :'四川'},
	{city : '广安',province :'四川'},
	{city : '达州',province :'四川'},
	{city : '雅安',province :'四川'},
	{city : '巴中',province :'四川'},
	{city : '资阳',province :'四川'},
	{city : '阿坝',province :'四川'},
	{city : '甘孜',province :'四川'},
	{city : '凉山',province :'四川'},
	{city : '贵阳',province :'四川'},
	{city : '六盘水',province :'四川'},
	{city : '遵义',province :'四川'},
	{city : '安顺',province :'四川'},
	{city : '铜仁',province :'四川'},
	{city : '黔西南',province :'四川'},
	{city : '毕节',province :'四川'},
	{city : '黔东南',province :'四川'},
	{city : '黔南',province :'四川'},
	{city : '昆明',province :'云南'},
	{city : '曲靖',province :'云南'},
	{city : '玉溪',province :'云南'},
	{city : '保山',province :'云南'},
	{city : '昭通',province :'云南'},
	{city : '楚雄',province :'云南'},
	{city : '红河',province :'云南'},
	{city : '文山',province :'云南'},
	{city : '思茅',province :'云南'},
	{city : '西双版纳',province :'云南'},
	{city : '大理',province :'云南'},
	{city : '德宏',province :'云南'},
	{city : '丽江',province :'云南'},
	{city : '怒江',province :'云南'},
	{city : '迪庆',province :'云南'},
	{city : '临沧',province :'云南'},
	{city : '拉萨',province :'西藏'},
	{city : '昌都',province :'西藏'},
	{city : '山南',province :'西藏'},
	{city : '日喀则',province :'西藏'},
	{city : '那曲',province :'西藏'},
	{city : '阿里',province :'西藏'},
	{city : '林芝',province :'西藏'},
	{city : '西安',province :'陕西'},
	{city : '铜川',province :'陕西'},
	{city : '宝鸡',province :'陕西'},
	{city : '咸阳',province :'陕西'},
	{city : '渭南',province :'陕西'},
	{city : '延安',province :'陕西'},
	{city : '汉中',province :'陕西'},
	{city : '榆林',province :'陕西'},
	{city : '安康',province :'陕西'},
	{city : '商洛',province :'陕西'},
	{city : '兰州',province :'甘肃'},
	{city : '嘉峪关',province :'甘肃'},
	{city : '金昌',province :'甘肃'},
	{city : '白银',province :'甘肃'},
	{city : '天水',province :'甘肃'},
	{city : '武威',province :'甘肃'},
	{city : '张掖',province :'甘肃'},
	{city : '平凉',province :'甘肃'},
	{city : '酒泉',province :'甘肃'},
	{city : '庆阳',province :'甘肃'},
	{city : '定西',province :'甘肃'},
	{city : '陇南',province :'甘肃'},
	{city : '临夏',province :'甘肃'},
	{city : '甘南',province :'甘肃'}, 
	{city : '西宁',province :'青海'},
	{city : '海东',province :'青海'},
	{city : '海北',province :'青海'},
	{city : '黄南',province :'青海'},
	{city : '海南',province :'青海'},
	{city : '果洛',province :'青海'},
	{city : '玉树',province :'青海'},
	{city : '海西',province :'青海'},
	{city : '银川',province :'宁夏'},
	{city : '石嘴山',province :'宁夏'},
	{city : '吴忠',province :'宁夏'},
	{city : '固原',province :'宁夏'},
	{city : '乌鲁木齐',province :'新疆'},
	{city : '克拉玛依',province :'新疆'},
	{city : '吐鲁番',province :'新疆'},
	{city : '哈密',province :'新疆'},
	{city : '昌吉',province :'新疆'},
	{city : '博尔塔拉',province :'新疆'},
	{city : '巴音郭楞',province :'新疆'},
	{city : '阿克苏',province :'新疆'},
	{city : '克孜勒苏',province :'新疆'},
	{city : '喀什',province :'新疆'},
	{city : '和田',province :'新疆'},
	{city : '伊犁',province :'新疆'},
	{city : '塔城',province :'新疆'},
	{city : '阿勒泰',province :'新疆'},
	{city : '石河子',province :'新疆'},
	{city : '台北',province :'台湾'},
	{city : '高雄',province :'台湾'},
	{city : '基隆',province :'台湾'},
	{city : '台中',province :'台湾'},
	{city : '台南',province :'台湾'},
	{city : '新竹',province :'台湾'},
	{city : '嘉义',province :'台湾'},
	{city : '香港',province :'香港'},
	{city : '澳门',province :'澳门'},
];